<?php
/**
 * DepEd position titles for dropdowns (apply loan / edit loan).
 * Based on DepEd plantilla positions – Teaching, School Administration, Related-Teaching & Non-Teaching.
 */
if (!isset($deped_position_options)) {
    $deped_position_options = [
        'Teaching' => [
            'Teacher I',
            'Teacher II',
            'Teacher III',
            'Teacher IV',
            'Teacher V',
            'Teacher VI',
            'Teacher VII',
            'Master Teacher I',
            'Master Teacher II',
            'Master Teacher III',
            'Master Teacher IV',
            'Master Teacher V',
            'Instructor I',
            'Instructor II',
            'Instructor III',
            'Special Education Teacher I',
            'Special Education Teacher II',
            'Special Education Teacher III',
            'Special Science Teacher I',
        ],
        'School Administration' => [
            'School Principal I',
            'School Principal II',
            'School Principal III',
            'School Principal IV',
            'Assistant School Principal I',
            'Assistant School Principal II',
            'Assistant School Principal III',
            'Head Teacher I',
            'Head Teacher II',
            'Head Teacher III',
            'Head Teacher IV',
            'Head Teacher V',
            'Head Teacher VI',
            'Tech-Voc School Administrator',
            'Special Schools Principal',
        ],
        'Related-Teaching & Non-Teaching' => [
            'Administrative Officer II',
            'Supervising Administrative Officer',
            'Administrative Assistant I',
            'Administrative Assistant II',
            'Administrative Assistant III',
            'Administrative Assistant IV',
            'Administrative Assistant V',
            'Administrative Assistant VI',
            'Administrative Aide I',
            'Administrative Aide III',
            'Administrative Aide IV',
            'Administrative Aide V',
            'Administrative Aide VI',
            'Guidance Counselor I',
            'Guidance Counselor II',
            'Guidance Counselor III',
            'Guidance Coordinator I',
            'Guidance Coordinator II',
            'Guidance Coordinator III',
            'Accountant I',
            'Accountant II',
            'Accountant III',
            'Security Guard I',
            'Security Guard II',
            'Watchman I',
        ],
    ];
}
